# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1b9e8b61ec859a648d841dbe91bce710e0b1f8b1ec2134391792003f019cae9f2819c90d667f15a2df6c51c7e4ab0d5a436abe3df945ef33b7c2dd8690e6e2ce

test:
  secret_key_base: a72c72fe341f51577c3233820f4353113b4d123d72dedbd3903390cb12c35f8d2ea4b444be29ae02ba8a8171159d3b6f608dc73487e028e8daec660653cc74bb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
